# Exercise 1


This exercise covers the necessary steps for getting ready in `R` and some basic concepts for setting up a well-structured `R` project. The lesson introduces how additional packages that provide useful functions for data science are made available and how spatial data is handled. The exercise concludes with the creation of your first map featuring movement data. 





**Learning Outcomes***

- You learn how to structure an `R` project.
- You can read movement data from a .csv-file into a `data.frame`
- You can convert spatial point data from a `data.frame` to a spatial object `sf`
- You can perform basic spatial operations on spatial objects in `R`
- You can produce simple maps of your spatial data using `ggplot2`
- You can produce simple maps of your spatial data using `tmap`


**Prerequisites***

Readings Skills from "R for Data Science" [@wickham2017]:

- RS1.1 Preface (16p, ix-xxiv)
- RS1.2 Chap2 Workflow basics (3p, 37-39)
- RS1.3 Chap4 Workflow scripts (3p, 77-79)
- RS1.4 Chap6 workflow projects (6p, 111-116)
- RS1.5 Chap8 Data Import with `readr` (21p)
- RS1.6 Chap13 Date and Times with `lubridate` (18p, 237-256)
